import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { RenderingSpec } from "../../../../src/types/blog-v3.js";
import { PATHS, DEV_SERVER } from "../config.js";
import type { ArticleLogger } from "../utils/logger.js";

/**
 * Agent 6 — Renderer (deterministic)
 *
 * Input  : RenderingSpec
 * Output : staging data file path + rendered URL + screenshot bytes
 *
 * Responsibilities :
 *   1. Persist the spec as a JSON file in docs/blog-migration/_staging/
 *      (one file per article — easy to inspect / merge later).
 *   2. Patch src/data/blog-articles-v3.ts with this article's entry.
 *      Read existing, splice in/replace the entry for this slug, write back.
 *   3. Wait for Next.js HMR to settle.
 *   4. Capture a Playwright screenshot of the rendered page.
 *
 * The dev server is expected to be running externally (`npm run dev`).
 * The state machine starts/stops it once for the whole migration run.
 */

import { chromium, type Browser } from "playwright";

let browser: Browser | null = null;
async function getBrowser(): Promise<Browser> {
  if (browser && browser.isConnected()) return browser;
  browser = await chromium.launch({ headless: true });
  return browser;
}

export async function closeBrowser(): Promise<void> {
  if (browser) {
    await browser.close();
    browser = null;
  }
}

export interface RendererInput {
  slug: string;
  spec: RenderingSpec;
}

export interface RendererOutput {
  stagingJsonPath: string;
  renderedUrl: string;
  /** Ordered array of base64-encoded PNG tiles (top-to-bottom of the page). */
  screenshotsBase64: string[];
  /** Filesystem paths matching screenshotsBase64. */
  screenshotPaths: string[];
}

function buildV3DataFile(specs: RenderingSpec[]): string {
  return `/**
 * Auto-generated by scripts/migrate/blog-pipeline. DO NOT EDIT MANUALLY.
 *
 * Each article is a fully-decided RenderingSpec V3 — the renderer is passive.
 * To modify content/design : edit docs/blog-design-rules.yaml (chat with
 * Claude) and re-run \`npm run blog:migrate -- --slugs=<slug>\`.
 */
import type { BlogArticleV3 } from "@/types/blog-v3";

export const BLOG_ARTICLES_V3: BlogArticleV3[] = ${JSON.stringify(specs, null, 2)} as const;

export const ACTIVE_BLOG_ARTICLES_V3 = BLOG_ARTICLES_V3.filter((a) => !a.skip);

export const BLOG_BY_SLUG_V3 = Object.fromEntries(
  BLOG_ARTICLES_V3.map((a) => [a.slug, a] as const),
);
`;
}

function loadExistingV3(): RenderingSpec[] {
  if (!existsSync(PATHS.v3DataFile)) return [];
  const txt = readFileSync(PATHS.v3DataFile, "utf8");
  const m = txt.match(/BLOG_ARTICLES_V3[^=]*=\s*(\[[\s\S]*\])\s*as const\s*;/);
  if (!m) return [];
  try {
    return JSON.parse(m[1]) as RenderingSpec[];
  } catch {
    return [];
  }
}

function spliceArticle(all: RenderingSpec[], spec: RenderingSpec): RenderingSpec[] {
  const idx = all.findIndex((a) => a.slug === spec.slug);
  if (idx === -1) {
    return [...all, spec];
  }
  const copy = [...all];
  copy[idx] = spec;
  return copy;
}

/**
 * Heading texts that mark the START of a separately-extracted section
 * (related links, FAQ, newsletter). The Designer should NOT emit these
 * as body headings — they're rendered by dedicated DS components
 * (RelatedArticlesFrame, FaqFrame). Post-process safety net.
 */
const SECTION_MARKER_HEADINGS = [
  "pour aller plus loin",
  "questions fréquentes",
  "questions frequentes",
  "faq",
  "recevez nos meilleurs articles",
  "réservez votre démo",
];

function dropSectionMarkerHeadings(spec: RenderingSpec): { spec: RenderingSpec; dropped: number } {
  const normalize = (s: string) =>
    s.toLowerCase().replace(/[?!.,:;]/g, "").replace(/\s+/g, " ").trim();
  let dropped = 0;
  const blocks = spec.blocks.filter((b) => {
    if (b.type !== "heading") return true;
    const text = normalize(b.text);
    const isMarker = SECTION_MARKER_HEADINGS.some((m) => text === m || text.startsWith(m));
    if (isMarker) {
      dropped++;
      return false;
    }
    return true;
  });
  return { spec: { ...spec, blocks }, dropped };
}

/**
 * DS Heading at level=4 forbids gradient (`useGradient = level !== 4`).
 * The Figma blog template demands gradient on every body subsection title.
 * Re-route any rogue level=4 emission to level=3 with gradient="primary".
 * Belt-and-suspenders : Designer prompt was updated to never emit level=4
 * in body but the LLM occasionally drifts.
 */
function fixLevel4Headings(spec: RenderingSpec): { spec: RenderingSpec; upgraded: number } {
  let upgraded = 0;
  const blocks = spec.blocks.map((b) => {
    if (b.type !== "heading" || b.level !== 4) return b;
    upgraded++;
    return { ...b, level: 3 as const, gradient: "primary" as const };
  });
  return { spec: { ...spec, blocks }, upgraded };
}

export async function runRenderer(
  input: RendererInput,
  logger: ArticleLogger,
): Promise<RendererOutput> {
  // Deterministic post-process : drop body headings that match a section
  // marker (those map to a separate DS frame, not to the prose body).
  let working = input.spec;
  const dropped = dropSectionMarkerHeadings(working);
  working = dropped.spec;
  if (dropped.dropped > 0) {
    logger.info("renderer", `dropped ${dropped.dropped} section-marker heading(s) from body`);
  }
  // Force every body heading to level=2/3 with gradient (DS contract: level=4 = solid).
  const upgraded = fixLevel4Headings(working);
  working = upgraded.spec;
  if (upgraded.upgraded > 0) {
    logger.info("renderer", `upgraded ${upgraded.upgraded} level=4 heading(s) → level=3 gradient`);
  }
  const effectiveSpec = working;

  // 1. Write staging JSON (always — easy debug).
  mkdirSync(PATHS.v3StagingDir, { recursive: true });
  const stagingJsonPath = join(PATHS.v3StagingDir, `${input.slug}.json`);
  writeFileSync(stagingJsonPath, JSON.stringify(effectiveSpec, null, 2));

  // 2. Patch the V3 data file in-place (single source of truth used by
  // the dev server). We always splice — if the article is being re-rendered
  // (retry), we overwrite.
  const all = loadExistingV3();
  const next = spliceArticle(all, effectiveSpec);
  writeFileSync(PATHS.v3DataFile, buildV3DataFile(next));
  logger.info(
    "renderer",
    `wrote spec → ${stagingJsonPath} ; v3 data file now has ${next.length} articles`,
  );

  // 3. Wait for Next.js HMR to settle.
  await new Promise((r) => setTimeout(r, DEV_SERVER.hotReloadSettleMs));

  // 4. Screenshot the rendered page.
  // Anthropic vision rejects images whose largest dim > 8000 px. Long blog
  // articles render 12000+ px tall. Strategy: clip the full page into a
  // tiled set of ≤ 7800 px slices and pass an ordered array to the auditor.
  const url = `${DEV_SERVER.url}/fr/blog/v3/${input.slug}`;
  const TILE_HEIGHT = 4000; // safe under Anthropic 8000px limit even with retina

  const b = await getBrowser();
  // Viewport height matches a tile — each viewport-screenshot is one tile.
  const page = await b.newPage({ viewport: { width: 1280, height: TILE_HEIGHT } });
  try {
    const resp = await page.goto(url, { waitUntil: "networkidle", timeout: 30000 });
    if (!resp || !resp.ok()) {
      throw new Error(`Renderer page goto returned status ${resp?.status() ?? "?"}`);
    }
    // Pre-scroll to trigger lazy loads.
    await page.evaluate(() =>
      new Promise<void>((resolve) => {
        let y = 0;
        const step = window.innerHeight * 0.8;
        const id = setInterval(() => {
          window.scrollTo(0, (y += step));
          if (y >= document.body.scrollHeight) {
            clearInterval(id);
            window.scrollTo(0, 0);
            setTimeout(() => resolve(), 600);
          }
        }, 100);
      }),
    );

    const pageHeight = (await page.evaluate(() => document.body.scrollHeight)) as number;
    const articleDir = join(PATHS.migrationDir, input.slug);
    mkdirSync(articleDir, { recursive: true });

    // Number of tiles = ceil(pageHeight / TILE_HEIGHT). Min 1.
    const tileCount = Math.max(1, Math.ceil(pageHeight / TILE_HEIGHT));
    const tiles: string[] = [];
    const tilesB64: string[] = [];
    for (let i = 0; i < tileCount; i++) {
      const y = i * TILE_HEIGHT;
      await page.evaluate((yy: number) => window.scrollTo(0, yy), y);
      // Let any sticky/parallax settle.
      await page.waitForTimeout(200);
      const tilePath = join(articleDir, `rendered-${String(i).padStart(2, "0")}.png`);
      // fullPage:false captures the viewport — guaranteed ≤ TILE_HEIGHT px tall.
      const buf = await page.screenshot({ fullPage: false, path: tilePath });
      tiles.push(tilePath);
      tilesB64.push(buf.toString("base64"));
    }
    logger.info(
      "renderer",
      `screenshot ok ${url} → ${tiles.length} tile(s) (page h=${pageHeight}px, viewport=${TILE_HEIGHT}px)`,
    );
    return { stagingJsonPath, renderedUrl: url, screenshotPaths: tiles, screenshotsBase64: tilesB64 };
  } finally {
    await page.close();
  }
}
