import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { RenderingSpec } from "../../../../src/types/blog-v3.js";
import { PATHS, DEV_SERVER } from "../config.js";
import type { ArticleLogger } from "../utils/logger.js";

/**
 * Agent 6 — Renderer (deterministic)
 *
 * Input  : RenderingSpec
 * Output : staging data file path + rendered URL + screenshot bytes
 *
 * Responsibilities :
 *   1. Persist the spec as a JSON file in docs/blog-migration/_staging/
 *      (one file per article — easy to inspect / merge later).
 *   2. Patch src/data/blog-articles-v3.ts with this article's entry.
 *      Read existing, splice in/replace the entry for this slug, write back.
 *   3. Wait for Next.js HMR to settle.
 *   4. Capture a Playwright screenshot of the rendered page.
 *
 * The dev server is expected to be running externally (`npm run dev`).
 * The state machine starts/stops it once for the whole migration run.
 */

import { chromium, type Browser } from "playwright";

let browser: Browser | null = null;
async function getBrowser(): Promise<Browser> {
  if (browser && browser.isConnected()) return browser;
  browser = await chromium.launch({ headless: true });
  return browser;
}

export async function closeBrowser(): Promise<void> {
  if (browser) {
    await browser.close();
    browser = null;
  }
}

export interface RendererInput {
  slug: string;
  spec: RenderingSpec;
}

export interface RendererOutput {
  stagingJsonPath: string;
  renderedUrl: string;
  screenshotBase64: string;
  screenshotPath: string;
}

function buildV3DataFile(specs: RenderingSpec[]): string {
  return `/**
 * Auto-generated by scripts/migrate/blog-pipeline. DO NOT EDIT MANUALLY.
 *
 * Each article is a fully-decided RenderingSpec V3 — the renderer is passive.
 * To modify content/design : edit docs/blog-design-rules.yaml (chat with
 * Claude) and re-run \`npm run blog:migrate -- --slugs=<slug>\`.
 */
import type { BlogArticleV3 } from "@/types/blog-v3";

export const BLOG_ARTICLES_V3: BlogArticleV3[] = ${JSON.stringify(specs, null, 2)} as const;

export const ACTIVE_BLOG_ARTICLES_V3 = BLOG_ARTICLES_V3.filter((a) => !a.skip);

export const BLOG_BY_SLUG_V3 = Object.fromEntries(
  BLOG_ARTICLES_V3.map((a) => [a.slug, a] as const),
);
`;
}

function loadExistingV3(): RenderingSpec[] {
  if (!existsSync(PATHS.v3DataFile)) return [];
  const txt = readFileSync(PATHS.v3DataFile, "utf8");
  const m = txt.match(/BLOG_ARTICLES_V3[^=]*=\s*(\[[\s\S]*\])\s*as const\s*;/);
  if (!m) return [];
  try {
    return JSON.parse(m[1]) as RenderingSpec[];
  } catch {
    return [];
  }
}

function spliceArticle(all: RenderingSpec[], spec: RenderingSpec): RenderingSpec[] {
  const idx = all.findIndex((a) => a.slug === spec.slug);
  if (idx === -1) {
    return [...all, spec];
  }
  const copy = [...all];
  copy[idx] = spec;
  return copy;
}

export async function runRenderer(
  input: RendererInput,
  logger: ArticleLogger,
): Promise<RendererOutput> {
  // 1. Write staging JSON (always — easy debug).
  mkdirSync(PATHS.v3StagingDir, { recursive: true });
  const stagingJsonPath = join(PATHS.v3StagingDir, `${input.slug}.json`);
  writeFileSync(stagingJsonPath, JSON.stringify(input.spec, null, 2));

  // 2. Patch the V3 data file in-place (single source of truth used by
  // the dev server). We always splice — if the article is being re-rendered
  // (retry), we overwrite.
  const all = loadExistingV3();
  const next = spliceArticle(all, input.spec);
  writeFileSync(PATHS.v3DataFile, buildV3DataFile(next));
  logger.info(
    "renderer",
    `wrote spec → ${stagingJsonPath} ; v3 data file now has ${next.length} articles`,
  );

  // 3. Wait for Next.js HMR to settle.
  await new Promise((r) => setTimeout(r, DEV_SERVER.hotReloadSettleMs));

  // 4. Screenshot the rendered page.
  const url = `${DEV_SERVER.url}/fr/blog/${input.slug}`;
  const b = await getBrowser();
  const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
  try {
    const resp = await page.goto(url, { waitUntil: "networkidle", timeout: 30000 });
    if (!resp || !resp.ok()) {
      throw new Error(`Renderer page goto returned status ${resp?.status() ?? "?"}`);
    }
    // Scroll the full page to trigger lazy loads, then screenshot.
    await page.evaluate(() =>
      new Promise<void>((resolve) => {
        let y = 0;
        const step = window.innerHeight * 0.8;
        const id = setInterval(() => {
          window.scrollTo(0, (y += step));
          if (y >= document.body.scrollHeight) {
            clearInterval(id);
            window.scrollTo(0, 0);
            setTimeout(() => resolve(), 500);
          }
        }, 100);
      }),
    );
    const screenshotPath = join(PATHS.migrationDir, input.slug, "rendered.png");
    mkdirSync(join(PATHS.migrationDir, input.slug), { recursive: true });
    const buf = await page.screenshot({ fullPage: true, path: screenshotPath });
    const screenshotBase64 = buf.toString("base64");
    logger.info("renderer", `screenshot ok ${url} → ${screenshotPath} (${(buf.length / 1024).toFixed(0)}KB)`);
    return { stagingJsonPath, renderedUrl: url, screenshotBase64, screenshotPath };
  } finally {
    await page.close();
  }
}
