/**
 * Landing page types — discriminated union of all section variants
 * found on airsaas.io landings (LP, Produit, Solution, Équipes).
 *
 * Generated by the parser at scripts/migrate/parse-landings-rebuild.py
 * → src/data/landings-v2/{lp,produit,solutions,equipes}.ts
 */

export interface LandingMeta {
  title: string;
  description: string;
  ogImage?: string | null;
}

/** Top hero with title + subtitle + primary CTA + optional mockup image. */
export interface HeroSection {
  type: "hero";
  /** First part of the title (often the gradient pill / accent). */
  titleHighlight?: string;
  /** Main title (rest of H1). */
  title: string;
  subtitle?: string;
  primaryCta?: { label: string; href: string };
  secondaryCta?: { label: string; href: string };
  /** Hero illustration / mockup image (full URL). */
  imageSrc?: string | null;
  imageAlt?: string;
}

/** Centered text-only section (intro / pillar / summary). */
export interface IntroSection {
  type: "intro";
  title?: string;
  body?: string; // inline HTML
}

/** Split section: title + body on one side, image on the other. */
export interface FeatureSplitSection {
  type: "feature-split";
  reversed?: boolean; // image left vs right
  title: string;
  titleHighlight?: string; // e.g. <strong> portion
  body?: string; // inline HTML (paragraphs, bullets)
  imageSrc?: string | null;
  imageAlt?: string;
  bullets?: string[];
}

/** Numbered bullet list with emojis (e.g. "Vous vous reconnaissez ?"). */
export interface PainPointsSection {
  type: "pain-points";
  emoji?: string;
  title: string;
  subtitle?: string;
  items: string[];
}

/** 4-col stat row. */
export interface StatsSection {
  type: "stats";
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  items: { value: string; label: string }[];
}

/** Logo bar (clients / press / partners). */
export interface LogoBarSection {
  type: "logo-bar";
  title?: string;
  variant?: "client" | "press" | "partner";
  logos: { src: string; alt: string }[];
}

/** Press quote cards (citations from media). */
export interface PressQuotesSection {
  type: "press-quotes";
  title?: string;
  quotes: { text: string; source: string; logoSrc?: string | null }[];
}

/** LinkedIn-style testimonials cards (3-col). */
export interface TestimonialsSection {
  type: "testimonials";
  title?: string;
  titleHighlight?: string;
  testimonials: {
    text: string;
    name: string;
    role?: string;
    company?: string;
    avatarSrc?: string | null;
    linkedinUrl?: string;
  }[];
}

/** Customer testimonials with photo + role. */
export interface CustomerTestimonialsSection {
  type: "customer-testimonials";
  title?: string;
  testimonials: {
    text: string;
    name: string;
    role?: string;
    avatarSrc?: string | null;
  }[];
}

/** Comparison table (sans/avec or avant/après). */
export interface ComparisonTableSection {
  type: "comparison-table";
  title?: string;
  columns: string[];
  rows: string[][];
}

/** Numbered steps (deployment, how it works). */
export interface StepsSection {
  type: "steps";
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  steps: { title: string; description?: string }[];
}

/** FAQ accordion. */
export interface FaqSection {
  type: "faq";
  title?: string;
  titleHighlight?: string;
  items: { question: string; answer: string }[];
}

/** Closing or mid-page CTA banner. */
export interface CtaSection {
  type: "cta";
  title: string;
  titleHighlight?: string;
  subtitle?: string;
  ctaLabel: string;
  ctaHref?: string;
  videoHref?: string;
}

/** Icon row (security badges, integrations). */
export interface IconRowSection {
  type: "icon-row";
  title?: string;
  subtitle?: string;
  items: { iconSrc?: string | null; label: string }[];
}

/** Related cards (cross-sell). */
export interface RelatedSection {
  type: "related";
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  items: { title: string; description?: string; imageSrc?: string | null; href: string }[];
}

/** Trust badges row (under hero). */
export interface TrustBadgesSection {
  type: "trust-badges";
  badges: { label: string; iconSrc?: string | null }[];
}

/** Generic fallback for unrecognized blocks. */
export interface RawSection {
  type: "raw";
  html: string;
}

export type LandingSection =
  | HeroSection
  | IntroSection
  | FeatureSplitSection
  | PainPointsSection
  | StatsSection
  | LogoBarSection
  | PressQuotesSection
  | TestimonialsSection
  | CustomerTestimonialsSection
  | ComparisonTableSection
  | StepsSection
  | FaqSection
  | CtaSection
  | IconRowSection
  | RelatedSection
  | TrustBadgesSection
  | RawSection;

export interface LandingPage {
  slug: string;
  type: "lp" | "produit" | "solution" | "equipe";
  meta: LandingMeta;
  sections: LandingSection[];
}
