/**
 * Landing page types — discriminated union of all section variants
 * found on airsaas.io landings (LP, Produit, Solution, Équipes).
 *
 * Generated by the parser at scripts/migrate/parse-landings-rebuild.py
 * → src/data/landings-v2/{lp,produit,solutions,equipes}.ts
 */

export interface LandingMeta {
  title: string;
  description: string;
  ogImage?: string | null;
}

/** Top hero with title + subtitle + primary CTA + optional mockup image. */
export interface HeroSection {
  type: "hero";
  /** First part of the title (often the gradient pill / accent). */
  titleHighlight?: string;
  /** Main title (rest of H1). */
  title: string;
  subtitle?: string;
  /** Optional inline-HTML body below the subtitle (extra paragraph). */
  body?: string;
  /** Optional bullet list rendered below the subtitle (live: trust tags). */
  bullets?: string[];
  primaryCta?: { label: string; href: string };
  secondaryCta?: { label: string; href: string };
  /** Hero illustration / mockup image (full URL). */
  imageSrc?: string | null;
  imageAlt?: string;
}

/** Centered text-only section (intro / pillar / summary). */
export interface IntroSection {
  type: "intro";
  title?: string | null;
  body?: string | null; // inline HTML
  /** Optional heading level — defaults to 2; some sub-headings emit as 3. */
  headingLevel?: 2 | 3 | 4;
  /** Sub-sections nested under this intro (rendered as H3 + body inside). */
  subSections?: { title?: string | null; body?: string | null }[];
}

/** Split section: title + body on one side, image on the other. */
export interface FeatureSplitSection {
  type: "feature-split";
  reversed?: boolean; // image left vs right
  title: string;
  titleHighlight?: string; // e.g. <strong> portion
  /** Optional small subtitle between title and body. */
  subtitle?: string;
  body?: string; // inline HTML (paragraphs, bullets)
  imageSrc?: string | null;
  imageAlt?: string;
  bullets?: string[];
  /** Inline CTA on the text side. */
  primaryCta?: { label: string; href: string };
  /** Optional H3 sub-blocks rendered as nested {title, body} pairs. */
  subSections?: { title?: string | null; body?: string | null }[];
}

/** Numbered bullet list with emojis (e.g. "Vous vous reconnaissez ?"). */
export interface PainPointsSection {
  type: "pain-points";
  emoji?: string;
  title: string;
  subtitle?: string;
  items: string[];
}

/** 4-col stat row. */
export interface StatsSection {
  type: "stats";
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  items: { value: string; label: string }[];
}

/** Logo bar (clients / press / partners). */
export interface LogoBarSection {
  type: "logo-bar";
  title?: string;
  subtitle?: string;
  variant?: "client" | "press" | "partner";
  logos: { src: string; alt: string }[];
}

/** Press quote cards (citations from media). */
export interface PressQuotesSection {
  type: "press-quotes";
  title?: string;
  quotes: { text: string; source: string; logoSrc?: string | null }[];
}

/** LinkedIn-style testimonials cards (3-col). */
export interface TestimonialsSection {
  type: "testimonials";
  title?: string;
  titleHighlight?: string;
  testimonials: {
    text: string;
    name: string;
    role?: string | null;
    company?: string | null;
    avatarSrc?: string | null;
    linkedinUrl?: string | null;
    /** Link to the full testimonial page (live: /fr/temoignages/{slug}). */
    href?: string | null;
  }[];
}

/** Customer testimonials with photo + role. */
export interface CustomerTestimonialsSection {
  type: "customer-testimonials";
  title?: string;
  subtitle?: string;
  /** Trailing CTA below the grid ("Voir les témoignages"). */
  primaryCta?: { label: string; href: string };
  testimonials: {
    /** Optional — many customer-testimonial layouts show metadata-only cards. */
    text?: string;
    name: string;
    role?: string;
    company?: string;
    avatarSrc?: string | null;
  }[];
}

/**
 * Comparison-table cell : plain string (legacy) OR an icon-with-text tuple
 * for the new variant (DS commit 96c61a5 — fixes audit finding [5.3]).
 */
export type ComparisonTableCell =
  | string
  | { type: "check" | "x"; text: string };

/** Comparison table (sans/avec or avant/après). */
export interface ComparisonTableSection {
  type: "comparison-table";
  title?: string;
  subtitle?: string;
  columns: string[];
  rows: ComparisonTableCell[][];
  /** Inline CTA below the table ("Réservez une démo"). */
  ctaLabel?: string;
  ctaHref?: string;
  primaryCta?: { label: string; href: string };
}

/** Numbered steps (deployment, how it works). */
export interface StepsSection {
  type: "steps";
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  steps: { title: string; description?: string }[];
}

/** FAQ accordion. */
export interface FaqSection {
  type: "faq";
  title?: string;
  titleHighlight?: string;
  items: { question: string; answer: string }[];
}

/** Closing or mid-page CTA banner. */
export interface CtaSection {
  type: "cta";
  title: string;
  titleHighlight?: string;
  subtitle?: string;
  ctaLabel: string;
  ctaHref?: string;
  videoHref?: string;
  /**
   * Optional dual-card CTA (live: "Réserver une démo" + "Découvrir vidéo").
   * When `items` is set with 2+ entries, the renderer can show a card grid
   * instead of the single ctaLabel/ctaHref.
   */
  items?: {
    title: string;
    description?: string;
    ctaLabel?: string;
    ctaHref?: string;
    videoHref?: string;
    iconSrc?: string | null;
  }[];
}

/** Icon row (security badges, integrations). */
export interface IconRowSection {
  type: "icon-row";
  title?: string;
  subtitle?: string;
  items: { iconSrc?: string | null; label: string }[];
}

/** Related cards (cross-sell). */
export interface RelatedSection {
  type: "related";
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  items: { title: string; description?: string; imageSrc?: string | null; href: string }[];
}

/** Trust badges row (under hero). */
export interface TrustBadgesSection {
  type: "trust-badges";
  title?: string;
  subtitle?: string;
  badges: { label: string; iconSrc?: string | null }[];
}

/** Generic fallback for unrecognized blocks. */
export interface RawSection {
  type: "raw";
  html: string;
}

/** Tab anchors row (typically hero-adjacent) — links to in-page sections. */
export interface TabsFrameSection {
  type: "tabs-frame";
  variant?: "light" | "dark";
  sticky?: boolean;
  tabs: { label: string; href: string }[];
}

/** Single highlight CTA card with tri-part gradient title. */
export interface CtaHighlightSection {
  type: "cta-highlight";
  titlePrefix: string;
  titleHighlight: string;
  titleSuffix?: string;
  subtitle?: string;
  ctaLabel: string;
  ctaHref?: string;
}

/** Numbered comparison list (pain-points alternate variant with value/desc tuples). */
export interface ComparisonFrameSection {
  type: "comparison-frame";
  emoji?: string;
  title: string;
  subtitle?: string;
  items: { value: string | number; description: string }[];
}

/** Non-sequential principles grid (DROP/ADD style, 2-3 columns). */
export interface PillarFrameSection {
  type: "pillar-frame";
  variant?: "light" | "dark";
  tag?: string;
  title: string;
  titleHighlight?: string;
  subtitle?: string;
  columns?: 2 | 3;
  pillars: {
    iconName?: string;
    title: string;
    description: string;
    example?: string;
    exampleLabel?: string;
  }[];
}

/** Vertically stacked zigzag highlights with big gradient values. */
export interface HighlightFrameSection {
  type: "highlight-frame";
  title: string;
  titleHighlight?: string;
  subtitle?: string;
  items: { value: string | number; description: string }[];
}

/** Stacked feature with title + list + bleed image. */
export interface FeatureStackedSection {
  type: "feature-stacked";
  titleGradient: string;
  titleDark?: string;
  titleDarkPrefix?: string;
  subtitle?: string;
  listItems?: string[];
  imageSrc?: string;
  imageAlt: string;
  variant?: "default" | "primary2";
}

/** Generic value proposition grid (flexible columns + cards). */
export interface ValuePropositionSection {
  type: "value-proposition";
  variant?: "light" | "dark";
  tag?: string;
  title: string;
  titleHighlight?: string;
  subtitle?: string;
  columns?: 2 | 3 | 4 | 5 | 6;
  items: {
    iconName?: string;
    title: string;
    description?: string;
  }[];
}

/** Rich steps frame with explicit numbers + icons (variant of "steps"). */
export interface StepsRichSection {
  type: "steps-rich";
  variant?: "light" | "dark";
  tag?: string;
  title: string;
  titleHighlight?: string;
  subtitle?: string;
  steps: {
    number?: number;
    iconName?: string;
    title: string;
    description: string;
  }[];
}

export type LandingSection =
  | HeroSection
  | IntroSection
  | FeatureSplitSection
  | PainPointsSection
  | StatsSection
  | LogoBarSection
  | PressQuotesSection
  | TestimonialsSection
  | CustomerTestimonialsSection
  | ComparisonTableSection
  | StepsSection
  | FaqSection
  | CtaSection
  | IconRowSection
  | RelatedSection
  | TrustBadgesSection
  | TabsFrameSection
  | CtaHighlightSection
  | ComparisonFrameSection
  | PillarFrameSection
  | HighlightFrameSection
  | FeatureStackedSection
  | ValuePropositionSection
  | StepsRichSection
  | RawSection;

export interface LandingPage {
  slug: string;
  type: "lp" | "produit" | "solution" | "equipe";
  meta: LandingMeta;
  sections: LandingSection[];
}
