import type { Metadata } from "next";
import { notFound } from "next/navigation";
import BlogPostPage from "@/components/pages/BlogPostPage";
import { BLOG_BY_SLUG_V3 } from "@/data/blog-articles-v3";
import { BLOG_INDEX_DATA } from "@/data/blog";
import { renderBlogBlocksV3 } from "@/components/blog/renderBlogBlocksV3";
import { estimateReadingTime } from "@/lib/reading-time";

/**
 * V3 preview route — drives the blog migration pipeline (Phase 2-4).
 * Reads from src/data/blog-articles-v3.ts (auto-generated by the renderer
 * agent) and feeds the same <BlogPostPage> template that V2 uses. The V3
 * spec carries every design decision (variant / gradient / widthMode) so
 * renderBlogBlocksV3 is fully passive.
 *
 * After Phase 5 this route will be deleted and /fr/blog/[slug] will read V3.
 */

// Force dynamic so the pipeline can hot-iterate without rebuilding params.
export const dynamic = "force-dynamic";

type RouteParams = { locale: string; slug: string };

const DEFAULT_HERO_IMAGE = "/assets/icons/AirSaas-logo 300x300.svg";
const DEFAULT_AUTHOR_AVATAR = "/assets/icons/airsaas-icon.svg";
const DEFAULT_THUMBNAIL = "/assets/icons/AirSaas-logo 300x300.svg";

export async function generateMetadata({
  params,
}: {
  params: Promise<RouteParams>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = BLOG_BY_SLUG_V3[slug];
  if (!article) return {};
  return { title: article.meta.title, description: article.meta.description };
}

const FRENCH_MONTHS = [
  "janvier", "février", "mars", "avril", "mai", "juin",
  "juillet", "août", "septembre", "octobre", "novembre", "décembre",
];

function formatPublishedDate(raw: string | null | undefined): string | undefined {
  if (!raw) return undefined;
  const m = raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);
  if (m) {
    const day = parseInt(m[1], 10);
    const month = parseInt(m[2], 10);
    const year = parseInt(m[3], 10);
    if (month >= 1 && month <= 12) {
      return `${day} ${FRENCH_MONTHS[month - 1]} ${year}`;
    }
  }
  return raw;
}

export default async function BlogArticleV3Route({
  params,
}: {
  params: Promise<RouteParams>;
}) {
  const { slug } = await params;
  const article = BLOG_BY_SLUG_V3[slug];
  if (!article || article.skip) notFound();

  const publishedDate = formatPublishedDate(
    article.meta.publishedDate || article.meta.author?.publishedDate,
  );
  const readingTime = estimateReadingTime(article.blocks);

  const heroImage = article.meta.heroImage?.src || DEFAULT_HERO_IMAGE;
  const heroImageAlt = article.meta.heroImage?.alt || article.meta.h1;
  const authorName = article.meta.author?.name || "AirSaas";
  const authorAvatarSrc = article.meta.author?.avatarSrc || DEFAULT_AUTHOR_AVATAR;

  const tableOfContents =
    article.layout === "centeredToc" && article.toc.length >= 3
      ? {
          title: "Sommaire",
          items: article.toc.map((t) => ({
            label: t.label,
            href: t.href,
            level: t.level as 2 | 3,
          })),
        }
      : undefined;

  const visibleFaq = article.faq.filter((f) => !f.hidden);
  const faq =
    article.toggles.showFaq && visibleFaq.length > 0
      ? {
          title: "Questions fréquentes",
          items: visibleFaq.slice(0, 10),
        }
      : undefined;

  const cta = article.toggles.showCta ? (article.customCta ?? BLOG_INDEX_DATA.cta) : undefined;

  return (
    <BlogPostPage
      navItems={BLOG_INDEX_DATA.navItems}
      navCtaLabel={BLOG_INDEX_DATA.navCtaLabel}
      navCtaHref={BLOG_INDEX_DATA.navCtaHref}
      loginLabel={BLOG_INDEX_DATA.loginLabel}
      loginHref={BLOG_INDEX_DATA.loginHref}
      topTagLabel="Le Blog"
      title={article.meta.h1 || article.meta.title}
      author={{
        name: authorName,
        avatarSrc: authorAvatarSrc,
        avatarAlt: authorName,
        categoryLabel: article.meta.author?.category ?? "Gestion de projet",
        categoryHref: "/fr/blog/articles",
        publishedByLabel: "Publié par",
        inLabel: "dans",
        datePrefix: "Le",
        publishedDate,
        readingTime,
      }}
      heroImageSrc={heroImage}
      heroImageAlt={heroImageAlt}
      tableOfContents={tableOfContents}
      articleBody={renderBlogBlocksV3(article.blocks)}
      newsletterCard={
        article.toggles.showNewsletter
          ? {
              title: "Recevez nos meilleurs articles",
              subtitle:
                "Une fois par mois, on vous envoie nos retours d'expérience pratiques sur la gestion de portefeuille projets.",
              placeholder: "votre@email.com",
              ctaLabel: "S'abonner",
              privacyText: "Pas de spam — désinscription en un clic.",
            }
          : undefined
      }
      faq={faq}
      cta={cta as typeof BLOG_INDEX_DATA.cta | undefined}
      footerColumns={BLOG_INDEX_DATA.footerColumns}
      copyright={`© ${new Date().getFullYear()} AirSaas — Made in France`}
      copyrightIcon={
        <span className="inline-flex items-center gap-[0.375rem]">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/assets/icons/airsaas-icon.svg"
            alt=""
            aria-hidden="true"
            width="18"
            height="18"
          />
          <span>🇫🇷</span>
        </span>
      }
    />
  );
}
